### ISSUE TITLE
Image tool does not work

### ISSUE THREAD

**Issue by Awilum** [editor-js/simple-image#13]
included 
<script src="https://cdn.jsdelivr.net/npm/@editorjs/simple-image@latest"></script>

``
   tools: {
  
     image: {
       class: SimpleImage,
       inlineToolbar: ['link'],
     },
``

but I can't insert images, tool is not displaying.

**Comment by mylastore** [comment]
same here image tool is not displaying 

` 
      image: {
          class: SimpleImage,
          inlineToolbar: true
        }`

**Comment by neSpecc** [comment]
Can't reproduce. Is it still happen?

**Comment by avdkishore** [comment]
> Can't reproduce. Is it still happen?

Yes, it is still happening

**Comment by jimjones26** [comment]
I am unable to get it to work either. I define it in the tool list, everything runs fine and no errors are produced in the console, but the image tool icon does not show up in the toolbar.

**Comment by neSpecc** [comment]
@jimjones26 this tool does not have a Toolbar Icon. See [Image](https://github.com/editor-js/image) Tool if you need file uploading.

**Comment by jimjones26** [comment]
Oh, so how do I get the simple-image plugin to work? I must be missing something from the documentation?

**Comment by jimjones26** [comment]
I have the following in the tools section of the config:
`image: {
          class: SimpleImage,
          inlineToolbar: true
        },`
But I see nothing on the UI

**Comment by jimjones26** [comment]
I'm at a loss guys, I'm not sure how to get the Simple Image plugin to work.

**Comment by hong-duc** [comment]
ah I get it, all I need is to paste a image link to the editor then it will appear. 
example: `https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg` :man_facepalming: 

The readme don't say anything about it, and I have to watch the gift very closely to understand the magic :rofl: 

Also if the link contain param `https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500` will not work

**Comment by jimjones26** [comment]
@hong-duc Thanks! I feel like an idiot! Pasting an image in works perfectly!

**Comment by quana2k49** [comment]
Today, i was tried SimpleImage but not working too! Image icon is not display at toolbar :<

**Comment by edmundmunday** [comment]
@jimjones26 - don't feel like an idiot, this behavior is incredibly unintuitive.

**Comment by Codth** [comment]
Still haven't figured out? The SimpleImage tool does not display !

**Comment by c0b41** [comment]
@Codth read the comment https://github.com/editor-js/simple-image/issues/13#issuecomment-558297272

**Comment by SohaibShafiq1** [comment]
> https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg

can you please paste you code here. I still not able to see the option in toolbar

**Comment by Siddharth2207** [comment]
> Ah I get it, all I need is to paste a image link to the editor then it will appear.
> example: `https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg` 
> 
> The readme don't say anything about it, and I have to watch the gift very closely to understand the magic 
> 
> Also if the link contain param `https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500` will not work

Thank you

**Comment by Ashik590** [comment]
Is it a good idea pasting link of img?

**Comment by edricgalentino** [comment]
But now, the new issue was the image url is using base64 url so it take so many memory and also makes my program get slower. It took quite long to see the image or even open the program. Any idea?

**Comment by kumawat30rahul** [comment]
my image upload or directly pasting to the editor is also not working,:

import Embed from "@editorjs/embed";
import Table from "@editorjs/table";
import Paragraph from "@editorjs/paragraph";
import List from "@editorjs/list";
import Warning from "@editorjs/warning";
import Code from "@editorjs/code";
import LinkTool from "@editorjs/link";
import Image from "@editorjs/image";
import Raw from "@editorjs/raw";
import Header from "@editorjs/header";
import Quote from "@editorjs/quote";
import Marker from "@editorjs/marker";
import CheckList from "@editorjs/checklist";
import Delimiter from "@editorjs/delimiter";
import InlineCode from "@editorjs/inline-code";
import SimpleImage from "@editorjs/simple-image";
import VideoTool from "simple-video-editorjs";

export const EDITOR_JS_TOOLS = {
  // NOTE: Paragraph is default tool. Declare only when you want to change paragraph option.
  // paragraph: Paragraph,
  header: Header,
  table: Table,
  list: List,
  warning: Warning,
  code: Code,
  linkTool: LinkTool,
  embed: {
    class: Embed,
    config: {
      services: {
        // Specify supported embed services (e.g., YouTube, Twitter, etc.)
        youtube: true,
        twitter: true,
        // Add more services as needed
      },
    },
  },
    image: Image,
    raw: Raw,
    quote: Quote,
    marker: Marker,
    checklist: CheckList,
    delimiter: Delimiter,
    inlineCode: InlineCode,
    simpleImage: SimpleImage,
};


this the error i am getting:
{body: '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta char…cess/task_queues.js:82:21)</pre>\n</body>\n</html>\n', code: 404, headers: {…}}
body
: 
"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>NotFoundError: Not Found<br> &nbsp; &nbsp;at C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\server\\/app.js:48:8<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:328:13)<br> &nbsp; &nbsp;at C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:346:12)<br> &nbsp; &nbsp;at next (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:280:10)<br> &nbsp; &nbsp;at C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:646:15<br> &nbsp; &nbsp;at next (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:265:14)<br> &nbsp; &nbsp;at Function.handle (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:175:3)<br> &nbsp; &nbsp;at router (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:47:12)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:328:13)<br> &nbsp; &nbsp;at C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:346:12)<br> &nbsp; &nbsp;at next (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:280:10)<br> &nbsp; &nbsp;at middleware (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\webpack-hot-middleware\\middleware.js:38:48)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:328:13)<br> &nbsp; &nbsp;at C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:346:12)<br> &nbsp; &nbsp;at next (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:280:10)<br> &nbsp; &nbsp;at C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\server\\/app.js:24:3<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:328:13)<br> &nbsp; &nbsp;at C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:346:12)<br> &nbsp; &nbsp;at next (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:280:10)<br> &nbsp; &nbsp;at cookieParser (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\cookie-parser\\index.js:71:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:328:13)<br> &nbsp; &nbsp;at C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:346:12)<br> &nbsp; &nbsp;at next (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:280:10)<br> &nbsp; &nbsp;at urlencodedParser (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\body-parser\\lib\\types\\urlencoded.js:82:7)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:328:13)<br> &nbsp; &nbsp;at C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:346:12)<br> &nbsp; &nbsp;at next (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\express\\lib\\router\\index.js:280:10)<br> &nbsp; &nbsp;at C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\body-parser\\lib\\read.js:137:5<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (async_hooks.js:197:9)<br> &nbsp; &nbsp;at invokeCallback (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\raw-body\\index.js:231:16)<br> &nbsp; &nbsp;at done (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\raw-body\\index.js:220:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (C:\\Users\\Aaqib\\Documents\\GitHub\\pallet_backoffice_ui\\node_modules\\raw-body\\index.js:280:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:387:35)<br> &nbsp; &nbsp;at endReadableNT (internal/streams/readable.js:1317:12)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:82:21)</pre>\n</body>\n</html>\n"
code
: 
404
headers
: 
access-control-allow-headers
: 
"Origin, X-Requested-With, Content-Type, Accept"
access-control-allow-origin
: 
"http://localhost:3001"
connection
: 
"keep-alive"
content-length
: 
"6161"
content-security-policy
: 
"default-src 'none'"
content-type
: 
"text/html; charset=utf-8"
date
: 
"Tue, 18 Jul 2023 12:38:10 GMT"
keep-alive
: 
"timeout=5"
x-content-type-options
: 
"nosniff"
x-powered-by
: 
"Express"
[[Prototype]]
: 
Object
[[Prototype]]
: 
Object

can anybody solve this.

**Comment by Laktus** [comment]
For some reason i get a 500 when i try to upload, care to explain why?
